### ISSUE TITLE
Update to ES6 format

### ISSUE THREAD

**Issue by kristianmandrup** [bonniee/learning-react-native#10]
React 0.13 and above are using ES6 syntax. Time for an update!

**Comment by tuxtux00** [comment]
I agree.
I have just bought the book and I find myself struggling because the examples are outdated.
Please update

**Comment by bonniee** [comment]
@tuxtux00 @kristianmandrup repo has just been updated to use ES6 syntax, and React Native 0.26.3. Thanks!
