### ISSUE TITLE
Application WeatherProject has not been registered

### ISSUE THREAD

**Issue by rkhayat** [bonniee/learning-react-native#15]
Build was successful, I believe this is a client side error.

`Application WeatherProject has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent`

**Comment by royjkim** [comment]
In my experience, you should run 'React packager'.
If you already run 'React packager', close it and 'react-native run-ios'(or android) again. Then 'React packager' will start again.
