### ISSUE TITLE
OpenWeathermap API in WeatherProject has changed 

### ISSUE THREAD

**Issue by rcooke88** [bonniee/learning-react-native#17]
As of 10/2015 the folks at OpenWeatherMap have required an API key to be appended to the url request.  The book example shows:

fetch('http://api.openweathermap.org/data/2.5/weather?q='
      + zip + '&units=imperial')

but this won't work.  I finally got it working using this:

fetch('http://api.openweathermap.org/data/2.5/weather?zip='
      + zip + '&,us&APPID=xxxxxxxxxxxxxxxxxxx&units=imperial')
replace the xxx's with your API key.  You'll need to make an account on their site to get a key.

Hope this saves someone some time as it took me a while to figure this out.

**Comment by benco420** [comment]
Thank you 👍 
It helped me.  I just got around to starting this book, and only into chapter 2 I am seeing a lot of things out of date 😦

**Comment by liaobaocheng** [comment]
Now the API had been changed to:
```
"http://api.openweathermap.org/data/2.5/weather?zip="+zip+",us&APPID=XXXXXXXXXXXXXXXXXXXXX&units=imperial"
```
I test it by using httpie
```
$ pip install httpie 
$ http "http://api.openweathermap.org/data/2.5/weather?zip=94040,us&APPID=XXXXXXXXXXXXXXXXXXXXX&units=imperial"
```
