### ISSUE TITLE
CameraRoll.getPhotos(tag, success, error) is deprecated.  Use the returned Promise instead

### ISSUE THREAD

**Issue by sbefort** [bonniee/learning-react-native#18]
camera_roll_example.js doesn't work.

**Comment by zqlcrow** [comment]
CameraRoll.getPhotos({first: 5}).done(
      (data) =>{
         console.log(data);
        this.setState({
          photoSource: {uri: data.edges[3].node.image.uri}
        })
      },
      (error) => {
        console.warn(error);
      }
    );
