### ISSUE TITLE
WeatherApp broken with react-native v0.29

### ISSUE THREAD

**Issue by mvolkmann** [bonniee/learning-react-native#22]
I tried changing package.json to contain this:

```
  "dependencies": {
    "react": "^15.2.0",
    "react-native": "^0.29.2"
  }
```

That breaks the app pretty bad. Any idea what changed that could do this?
The text "Current weather for" is no longer visible and the weather description is overlapped by the temperature.

**Comment by aterrel** [comment]
I think this is the same issue as #23 

Works much better removing flex:1 in zipContainer and mainText styles
