### ISSUE TITLE
Impossible to launch test application

### ISSUE THREAD

**Issue by jealeroux** [bonniee/learning-react-native#3]
Hello,

I am new to react native and reading your book. I have completed the weather app from the Facebook template with no problem. 

I got some issues when I tried to compile your example. I should miss a step but I don't know which one. 

Hope you can help,

Jean-Philippe

$ npm install
$ npm start

> Bestsellers@0.0.1 start /Users/jp1/Documents/Dev/reactnative/learning-react-native/Bestsellers
> node_modules/react-native/packager/packager.sh

Could not find dependencies.
Ensure dependencies are installed - run 'npm install' from project root.

macbook-pro-de-jean-philippe:Bestsellers jp1$ npm install
npm WARN deprecated babel-core@5.8.21: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN prefer global react-tools@0.14.0-beta1 should be installed with -g
npm WARN prefer global babel@5.8.21 should be installed with -g

> fsevents@1.0.6 install /Users/jp1/Documents/Dev/reactnative/learning-react-native/Bestsellers/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/jp1/Documents/Dev/reactnative/learning-react-native/Bestsellers/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> bufferutil@1.2.1 install /Users/jp1/Documents/Dev/reactnative/learning-react-native/Bestsellers/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/jp1/Documents/Dev/reactnative/learning-react-native/Bestsellers/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> spawn-sync@1.0.13 postinstall /Users/jp1/Documents/Dev/reactnative/learning-react-native/Bestsellers/node_modules/spawn-sync
> node postinstall

Bestsellers@0.0.1 /Users/jp1/Documents/Dev/reactnative/learning-react-native/Bestsellers
└─┬ react-native@0.11.4 
  ├── absolute-path@0.0.0 
  ├─┬ babel@5.8.21

**Comment by bonniee** [comment]
Hi there! It's hard for me to tell what's going on from this output. Did you make sure to run `npm start` again from within the `Bestsellers` directory after running `npm install`?

Are you having this issue with other examples in this repo, or just the Bestsellers project? Have you successfully compiled and run other React Native applications?

If not, try the following in a fresh directory:
```
npm install -g react-native-cli
react-native init TestProject
```
Can you run the new `TestProject` application?

**Comment by jealeroux** [comment]
Hi there! It's hard for me to tell what's going on from this output. Did you make sure to run npm start again from within the Bestsellers directory after running npm install?
-> Yes I did but I have the same problem with all of them. 

Nevertheless it work fine if i run npm install -g react-native-cli &  react-native init TestProject copying and paste your code from github. I have tested WeatherProject and PressDemo successfully.

**Comment by bonniee** [comment]
Thanks for the update! I unfortunately can't replicate the issue on either of my machines. This might be due to changes in React Native's setup code, which has undergone some major changes over the last six months.

I'm glad that starting a fresh project and copying over the relevant component files worked for you! If you submit a PR with the "fresh" versions I'd be happy to test it & merge. I should probably do that myself, but it'll likely be a few weeks before I get around to it.

**Comment by barefootford** [comment]
I'm running into the same issues. I'm not positive, but I think this is the same issue: 
https://github.com/facebook/react-native/issues/1758

**Comment by bonniee** [comment]
@barefootford thanks for reporting, I'll try and get a fix out this week.

**Comment by guilsa** [comment]
Similar issue as well for me.

```
cd .../learning-react-native/touch
npm install
> Touch@0.0.1 start /Users/Guigui/Dev/temp/react-native/learning-react-native/Touch
> node_modules/react-native/packager/packager.sh


Could not find dependencies.
Ensure dependencies are installed - run 'npm install' from project root.
```

From React Packager:

```
Could not find dependencies.
Ensure dependencies are installed - run 'npm install' from project root.

Process terminated. Press <enter> to close the window
```

Xcode issues:

![image](https://cloud.githubusercontent.com/assets/6107640/14128105/92f18136-f5d2-11e5-9baf-316792c13439.png)

**Comment by rochestb** [comment]
I just updated the versions and it worked. 
 
```
{
    "name": "WeatherProject",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "start": "node_modules/react-native/packager/packager.sh"
    },
    "dependencies": {
      "react": "^0.14.8",
      "react-native": "^0.25.1"
  
    }
 }
```

**Comment by stabenfeldt** [comment]
@bonniee, how far away are you from getting the examples fixed? I bought your book yesterday, but can't get any of the examples running. Must say that was a big disappointment, as the book appear to be well written.
The best would be if the examples worked with the latest version of React, but a `package.json` with compatible version would also be better than nothing.

**Comment by stabenfeldt** [comment]
I found a fork that has a working version of the **WeatherProject**.
I havn't tested the others, but they might work.. :-)

https://github.com/ebabel-eu/learning-react-native

**Comment by bonniee** [comment]
@stabenfeldt hi! Thanks for writing. The samples are now updated with react-native 0.26.3, and should run. As before, each individual project has a `package.json` specifying its dependencies.
