### ISSUE TITLE
PanDemo returns an error "You are setting the style `{ left: ... }` as a prop"

### ISSUE THREAD

**Issue by jealeroux** [bonniee/learning-react-native#4]
Hello,

When I am testing the PanDemo I got the following error message "[tid:com.facebook.React.JavaScript] You are setting the style `{ left: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { left: ... }}`"

Not sure what is wrong in the code,

Thanks again for your help,

JP

**Comment by bonniee** [comment]
@jealeroux the fix in #2 should help you out. Thanks!
