### ISSUE TITLE
Build error: 'RCTRootView.h' file not found

### ISSUE THREAD

**Issue by cjboorman** [bonniee/learning-react-native#47]
I cloned your repository locally, then I built the WeatherProject, but I got several build errors - all related to not being able to find React Native files.

![image](https://cloud.githubusercontent.com/assets/2146633/23272392/f2441d1a-f9af-11e6-8921-579ea3ad91b7.png)

I tried running "npm install|", but that didn't help.

**Comment by zhaozigeng** [comment]
1.npm install
2.react-native upgrade
